//GROUPS
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';
export const ADD_GROUP = 'ADD_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
//ALUMNS
export const FETCH_ALUMNOS = 'FETCH_ALUMNOS';
export const FETCH_ALUMNO = 'FETCH_ALUMNO';
export const ADD_ALUMNO = 'ADD_ALUMNO';
export const UPDATE_ALUMNO = 'UPDATE_ALUMNO';
export const DELETE_ALUMNO = 'DELETE_ALUMNO';
export const DELETE_ALUMNOS = 'DELETE_ALUMNOS'
export const FETCH_ALUMNOS_BY_GROUP = 'FETCH_ALUMNOS_BY_GROUP';
//TRIMESTRES
export const FETCH_TRIMESTRES = 'FETCH_TRIMESTRES';
export const FETCH_TRIMESTRE = 'FETCH_TRIMESTRE';
export const DELETE_TRIMESTRE = 'DELETE_TRIMESTRE';
export const ADD_TRIMESTRE = 'ADD_TRIESTRE';
export const UPDATE_TRIMESTRE = 'UPDATE_TRIMESTRE';
//PARCIALES
export const ADD_PARCIAL = 'ADD_PARCIAL';
export const FETCH_PARCIALES = 'FETCH_PARCIALES'
export const FETCH_PARCIAL = 'FETCH_PARCIAL';
export const UPDATE_PARCIAL = 'UPDATE_PARCIAL';
export const DELETE_PARCIAL = 'DELETE_PARCIAL';
//REALIZA
export const FETCH_REALIZAS = 'FETCH_REALIZAS';
export const ADD_REALIZA = 'ADD_REALIZA';
export const FETCH_REALIZA = 'FETCH_REALIZA';
export const FETCH_REALIZA_BY_TRIMESTRE = 'FETCH_REALIZA_BY_TRIMESTRE';
export const FETCH_REALIZA_BY_TRIMESTRE_GRUPO = 'FETCH_REALIZA_BY_TRIMESTRE_GRUPO';
export const FETCH_REALIZA_BY_ALUMNO_TRIMESTRE = 'FETCH_REALIZA_BY_ALUMNO_TRIMESTRE';
export const UPDATE_REALIZA = 'UPDATE_REALIZA';
export const DELETE_REALIZA = 'DELETE_REALIZA';
//FINALES
export const ADD_FINAL = 'ADD_FINAL';
export const FETCH_FINALES = 'FETCH_FINALES';
export const FETCH_FINAL = 'FETCH_FINAL';
export const UPDATE_FINAL = 'UPDATE_FINAL';
export const DELETE_FINAL = 'DELETE_FINAL';
export const FETCH_FINALES_BY_TRIMESTRE_ALUMNO = 'FETCH_FINALES_BY_TRIMESTRE_ALUMNO';

